- hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Deploy web page
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
